### PR TITLE
Avoid hardcoding year values

### LINKED ISSUE #660: Acceptance tests will be broken on 1 Jan 2023
## Describe the Bug
I was reading the acceptance tests to understand how to deal with litmus. While checking https://github.com/puppetlabs/puppetlabs-ntp/blob/main/spec/acceptance/integration_ntp_spec.rb I found years 2022 and 2023 are hardcoded there. So those tests are going to be broken in a month.

## Expected Behavior
I'd expect the tests to get the current year and deal with it instead of using hardcoded 2022.

### PR DESCRIPTION
**Pull request by binford2k**
Fixes #660 long term

### CODE REVIEW

**Review by david22swan — APPROVED** [review]
LGTM

Kinda embarrassed that none of us ever thought of this before

File: spec/acceptance/integration_ntp_spec.rb [hunk 1]
```diff
@@ -27,26 +27,26 @@ class { 'ntp': }
...
       it 'disable ntp auto-sync' do
         result = run_shell('timedatectl set-ntp false')
         expect(result.exit_code).to eq(0)
       end
 
-      it 'go forward to 2024' do
+      it 'go forward to to next year' do
         result = run_shell('date --set="$(date --date="next year")"')
-        expect(result.stdout).to match(%r{2024})
+        expect(result.stdout).to match(%r{#{Time.now.year.succ}})
```
Comment (spotter-puppet) [inline spec/acceptance/integration_ntp_spec.rb:43]: Time.now.year.succ is deprecated since 1.9.2 and will break when we move to Ruby 3.x.
```suggestion
        expect(result.stdout).to match(%r{#{Time.now.year+1}})
```

File: spec/acceptance/integration_ntp_spec.rb [hunk 2]
```diff
@@ -27,26 +27,26 @@ class { 'ntp': }
...
         expect(result.exit_code).to eq(0)
       end
 
-      it 'changed 2024' do
+      it 'changed to next year' do
         result = run_shell('date')
-        expect(result.stdout).to match(%r{2024})
+        expect(result.stdout).to match(%r{#{Time.now.year.succ}})
```
Comment (spotter-puppet) [inline spec/acceptance/integration_ntp_spec.rb:49]: Time.now.year.succ is deprecated since 1.9.2 and will break when we move to Ruby 3.x.
```suggestion
        expect(result.stdout).to match(%r{#{Time.now.year+1}})
```

**Comment by LukasAud** [comment]
Looks like there are some Rubocop issues blocking the CI. If you could address those, @binford2k, this PR should be an easy review/merge.

File: spec/acceptance/integration_ntp_spec.rb [hunk 3]
```diff
@@ -27,26 +27,26 @@ class { 'ntp': }
...
       it 'disable ntp auto-sync' do
         result = run_shell('timedatectl set-ntp false')
         expect(result.exit_code).to eq(0)
       end
 
-      it 'go forward to 2024' do
+      it 'go forward to to next year' do
         result = run_shell('date --set="$(date --date="next year")"')
-        expect(result.stdout).to match(%r{2024})
+        expect(result.stdout).to match(%r{#{Time.now.year+1}})
```
Comment (LukasAud) [inline spec/acceptance/integration_ntp_spec.rb:43]: I think you need to include a couple of spaces here to keep Rubocop happy
```suggestion
        expect(result.stdout).to match(%r{#{Time.now.year + 1}})
```

File: spec/acceptance/integration_ntp_spec.rb [hunk 4]
```diff
@@ -27,26 +27,26 @@ class { 'ntp': }
...
         expect(result.exit_code).to eq(0)
       end
 
-      it 'changed 2024' do
+      it 'changed to next year' do
         result = run_shell('date')
-        expect(result.stdout).to match(%r{2024})
+        expect(result.stdout).to match(%r{#{Time.now.year+1}})
```
Comment (LukasAud) [inline spec/acceptance/integration_ntp_spec.rb:49]: Same thing here
```suggestion
        expect(result.stdout).to match(%r{#{Time.now.year + 1}})
```

**Review by LukasAud — CHANGES_REQUESTED** [review]
Couple of wee adjustments needed before we can merge.

**Review by jordanbreen28 — APPROVED** [review]
